### ISSUE TITLE
Doesn't respect `max-line-length`

### ISSUE THREAD

**Issue by thorncp** [houndci/python#5]
The `max-line-length` config value seems to be ignored. There's a [suggestion](http://stackoverflow.com/questions/28436382/flake8-not-picking-up-config-file) that this was a regression with a previous version of pep8, however testing the latest version locally did not fix the problem.

**Comment by teoljungberg** [comment]
I'm unsure if this is related to it, but Hound commented on [this](https://github.com/thoughtbot/retul-bike-fit/pull/119/files#r42119345) twice

**Comment by nickstenning** [comment]
I think I know what the issue is here. Both [flake8](https://github.com/PyCQA/flake8/blob/16686132c12dd22fd664bd117d99a976cd9874f2/flake8/main.py#L96) and the underlying [pep8](https://github.com/PyCQA/pycodestyle/blob/53a24414787f93ec11beb18e7d60ba773c978eb8/pep8.py#L2058) contain code for normalising and typecasting options read from a .ini file.

In particular, the internal option names are `lower_underscored_names` while the config file keys are `lower-dashed-names`. So the `max-line-length` option is being completely ignored by `flake8.engine.get_style_guide()` -- it should instead be `max_line_length` and the value should be typechecked to integer before passing it along.

I'll try and find the time to work up a patch for this.

**Comment by nickstenning** [comment]
The most straightforward way to fix this would appear to be to write the config to a temporary file and then pass that as `config_file` to `flake8.main.get_style_guide` (which would hit [this code](https://github.com/PyCQA/pycodestyle/blob/53a24414787f93ec11beb18e7d60ba773c978eb8/pep8.py#L1819)).

But I'm guessing the runtime requirements of Hound would mean that we don't really want to do that? Thoughts, @thorncp?

The alternative is pretty ugly, as I think it's going to involve importing some decent-sized chunks of the pep8 CLI code in order to reproduce what [`read_config`](https://github.com/PyCQA/pycodestyle/blob/53a24414787f93ec11beb18e7d60ba773c978eb8/pep8.py#L2008) does without hitting the disk.

**Comment by thorncp** [comment]
Having to create a temporary file for the purposes of normalizing the config keys is a little odd, but I can't think of any technical requirements that would prevent us from doing it. It's entirely possible there's more to it that I'm not understanding.

Does using `max_line_length` as the key in your config file work? Would that be an acceptable workaround?

**Comment by nickstenning** [comment]
Unfortunately just using `max_line_length` won't work, as the `StyleGuide` will then throw because the value isn't an int.

The problem is basically that `get_style_guide` is not intended to be used with options pulled straight from a `.ini` file, and the factoring in flake8 and pep8 is such that it's hard to reuse the normalisation code in there without a file on disk (and not, say, the contents of a config file).

Perhaps a better way to fix this would be to submit some patches upstream. Maybe we could do the tempfile solution in Hound as a temporary measure until we have better upstream APIs?

**Comment by thorncp** [comment]
@nickstenning I think that's a totally feasible temporary solution. There's a larger movement within the Hound team to start using the CLIs of the various linters, for issues like this (each linter has its own oddities when using the code directly), and that's probably the long term solution. The Python linter does not see a lot of use (at least in part because it's still beta and we haven't really announced it), so it won't be the highest priority thing to work on for a bit. If you like to take a stab at it, I'd be happy review it.
